create table Person(
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName varchar(100) UNIQUE,
    yearOfBirth int
);

create table Book(
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(person_id) ON DELETE SET NULL,
    name varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    yearProduction int NOT NULL
);
SELECT * FROM Person;
SELECT * FROM Book;
INSERT INTO Person(fullname, yearofbirth) VALUES('Иванов Иван Иванович', '1980');
INSERT INTO Book(name, person_id, yearproduction) VALUES('Волшебная гора', 1, 1924);
DROP TABLE Book
INSERT INTO Book(name, author, yearproduction) VALUES('Волшебная гора', 'Томас Манн', 1924); -- Можно добавить книгу без владельца
DELETE FROM Book WHERE book_id=4;
UPDATE Book SET person_id=2 WHERE book_id=1;
SELECT Person.* FROM Book JOIN Person ON Person.person_id = Book.person_id WHERE book_id=2